name: CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test
      
    - name: Despliegue simulado
      run: echo "Despliegue exitoso"
